### ISSUE TITLE
Some known vulnerabilities

### ISSUE THREAD

**Issue by yarons** [Maagan-Michael/net-n#1]
I'm working with Snyk to scan our code.
So far we've discovered some issues related to react-scripts 5.0.1 (Which is the latest version).
The specific vulnerable packages are:
1. nth-check < 2.0.1 (2.1.1 available, manual override is possible - https://github.com/facebook/create-react-app/issues/13364).
2. css-what < 5.0.1 (6.1.0 available).
3. postcss < 8.4.31 (latest).

Fixing these will dismiss the warnings and will allow working without any known risks until new ones are discovered.
Thanks :)

**Comment by nathanschwarz** [comment]
I moved the project to `vite` instead of `react-scripts`, the related vulnerabilities are now patched
