### ISSUE TITLE
[UI] RTL Adjustments

### ISSUE THREAD

**Issue by yarons** [Maagan-Michael/net-n#2]
Required for Hebrew translation.

**Comment by nathanschwarz** [comment]
This can easily be done by adding a single class to the top of the react tree.
This should also be applied to the following components positions :
- [ ] reverse the table header
- [ ] [desktop] move the app title and search to the right
- [ ] [search]: reverse the order of internal components (icon, input, filter button)

**Comment by nathanschwarz** [comment]
Rtl is now fully supported
