### ISSUE TITLE
[Backend + UI] Exclude network equipment or ports

### ISSUE THREAD

**Issue by yarons** [Maagan-Michael/net-n#8]
The initiation process of the system should include a discovery of all the possible network routers in the IMC and correlate that with the router details we've fetched from Ma'alé with an option to restrict modifications on certain equipment so we won't end up modifying live ports for uninvolved equipment.
Same goes for ports, sometimes there's commercial equipment or chaining of routers that requires restricting of ports with a description in a way that the user will get a prompt that this is a protected port (due to X) and the user will have to acknowledge that action so it won't be by mistake.

**Comment by nathanschwarz** [comment]
- [ ] [backend] : add `restrictedPorts: [int]` to the `switches` schema and I/O
- [ ] [backend] : add restrictedMode: boolean` to the `switches` schema and I/O
- [ ] [frontend]: add both new input and the description input into the form
- [ ] [frontend]: add a form validation when either `specified port in restrictedPorts` or `restrictedMode == true`

**Comment by yarons** [comment]
We may also need to add some description (another DB field) to explain why this port is taken.

**Comment by nathanschwarz** [comment]
@yarons if  `connection.autoUpdate == true` should we allow for `connection.toggleDate` to be set ? Or it only concerns the syncModule ?

**Comment by nathanschwarz** [comment]
fully implemented as of commit:7126b49b26287e0f88a099b0dc6c9cb9ac28453e
